# Generated by Django 3.2.19 on 2023-05-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('userid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('person_1', models.CharField(max_length=50)),
                ('person_2', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
