# Generated by Django 3.2.19 on 2023-05-18 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('person_1', models.CharField(max_length=50)),
                ('person_2', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('imagepath', models.CharField(default="'images/love.png'", max_length=50, null=True)),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='portals.users')),
            ],
            options={
                'db_table': 'images_DB',
            },
        ),
    ]
